# Setup
title:        Catchthatbus Blog
tagline:      Book Bus Ticket Online Malaysia Singapore
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Catchthatbus.
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown