# Setup
title:        Catchthatbus Blog
tagline:      Book Bus Ticket Online Malaysia Singapore
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TEAMCTB
  url:        http://www.Catchthatbus.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown